<a href="https://colab.research.google.com/github/jasonhckim/Bagging_boosting_project/blob/main/Bagging_boosting_project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [517]:
## Section 1

In [518]:
# importing libraries
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')
from scipy.stats import zscore

In [519]:
#Loading the data
df = pd.read_csv('/content/talking_data.csv')

In [520]:
#
df.head()

ip  app  device  ...           click_time  attributed_time is_attributed
0   87540   12       1  ...  2017-11-07 09:30:38              NaN             0
1  105560   25       1  ...  2017-11-07 13:40:27              NaN             0
2  101424   12       1  ...  2017-11-07 18:05:24              NaN             0
3   94584   13       1  ...  2017-11-07 04:58:08              NaN             0
4   68413   12       1  ...  2017-11-09 09:00:09              NaN             0

[5 rows x 8 columns]

In [521]:
df['is_attributed'].value_counts()

0    99773
1      227
Name: is_attributed, dtype: int64

In [522]:
df.describe()

ip           app  ...        channel  is_attributed
count  100000.000000  100000.00000  ...  100000.000000  100000.000000
mean    91255.879670      12.04788  ...     268.832460       0.002270
std     69835.553661      14.94150  ...     129.724248       0.047591
min         9.000000       1.00000  ...       3.000000       0.000000
25%     40552.000000       3.00000  ...     145.000000       0.000000
50%     79827.000000      12.00000  ...     258.000000       0.000000
75%    118252.000000      15.00000  ...     379.000000       0.000000
max    364757.000000     551.00000  ...     498.000000       1.000000

[8 rows x 6 columns]

In [523]:
df.shape

(100000, 8)

In [524]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 8 columns):
 #   Column           Non-Null Count   Dtype 
---  ------           --------------   ----- 
 0   ip               100000 non-null  int64 
 1   app              100000 non-null  int64 
 2   device           100000 non-null  int64 
 3   os               100000 non-null  int64 
 4   channel          100000 non-null  int64 
 5   click_time       100000 non-null  object
 6   attributed_time  227 non-null     object
 7   is_attributed    100000 non-null  int64 
dtypes: int64(6), object(2)
memory usage: 6.1+ MB


In [525]:
miss_val = df.isna().sum()
miss_val

ip                     0
app                    0
device                 0
os                     0
channel                0
click_time             0
attributed_time    99773
is_attributed          0
dtype: int64

In [526]:
## Section 2

In [527]:
col_uni = df.nunique(axis = 0)
col_uni

ip                 34857
app                  161
device               100
os                   130
channel              161
click_time         80350
attributed_time      227
is_attributed          2
dtype: int64

In [528]:
df['ip'].nunique()

34857

In [529]:
df['app'].nunique()

161

In [530]:
df['device'].nunique()

100

In [531]:
df['os'].nunique()

130

In [532]:
df['channel'].nunique()

161

In [533]:
df['click_time'].nunique()

80350

In [534]:
df['attributed_time'].nunique()

227

In [535]:
df['is_attributed'].nunique()

2

In [536]:
## Section 3

In [537]:
removals = df['app'].value_counts().reset_index()
removals = removals[removals['app']>20]['index'].values

In [538]:
rdf1 = df[df['app'].isin(removals)]
print(rdf1)

           ip  app  device  ...           click_time  attributed_time is_attributed
0       87540   12       1  ...  2017-11-07 09:30:38              NaN             0
1      105560   25       1  ...  2017-11-07 13:40:27              NaN             0
2      101424   12       1  ...  2017-11-07 18:05:24              NaN             0
3       94584   13       1  ...  2017-11-07 04:58:08              NaN             0
4       68413   12       1  ...  2017-11-09 09:00:09              NaN             0
...       ...  ...     ...  ...                  ...              ...           ...
99995  124883   11       1  ...  2017-11-09 13:25:41              NaN             0
99996   85150    9       1  ...  2017-11-07 11:25:43              NaN             0
99997   18839    3       1  ...  2017-11-08 11:38:42              NaN             0
99998  114276   15       1  ...  2017-11-08 17:55:21              NaN             0
99999  119349   14       1  ...  2017-11-07 14:32:27              NaN       

In [539]:
rdf1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 99546 entries, 0 to 99999
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   ip               99546 non-null  int64 
 1   app              99546 non-null  int64 
 2   device           99546 non-null  int64 
 3   os               99546 non-null  int64 
 4   channel          99546 non-null  int64 
 5   click_time       99546 non-null  object
 6   attributed_time  197 non-null    object
 7   is_attributed    99546 non-null  int64 
dtypes: int64(6), object(2)
memory usage: 6.8+ MB


In [540]:
## Section 4

**4. By using Pandas derive new features such as - 'day_of_week' , 'day_of_year' , 'month' , and 'hour' as                  float/int datatypes using the 'click_time' column . Add the newly derived columns in original dataset.**

In [541]:
df['click_time'] = pd.to_datetime(df['click_time'])
df['day_of_week'] = df['click_time'].dt.day_name()
df['day_of_year'] = df['click_time'].dt.year
df['month'] = df['click_time'].dt.month
df['hour'] = df['click_time'].dt.hour
df = df.drop(['attributed_time','day_of_week','click_time'],axis=1)

In [542]:
df.head()

ip  app  device  os  channel  is_attributed  day_of_year  month  hour
0   87540   12       1  13      497              0         2017     11     9
1  105560   25       1  17      259              0         2017     11    13
2  101424   12       1  19      212              0         2017     11    18
3   94584   13       1  13      477              0         2017     11     4
4   68413   12       1   1      178              0         2017     11     9

In [543]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 9 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   ip             100000 non-null  int64
 1   app            100000 non-null  int64
 2   device         100000 non-null  int64
 3   os             100000 non-null  int64
 4   channel        100000 non-null  int64
 5   is_attributed  100000 non-null  int64
 6   day_of_year    100000 non-null  int64
 7   month          100000 non-null  int64
 8   hour           100000 non-null  int64
dtypes: int64(9)
memory usage: 6.9 MB


In [544]:
## Section 5

**5. Divide the data into training and testing subsets into 80:20 ratio(Train_data = 80% , Testing_data = 20%) and
     check the average download rates('is_attributed') for train and test data, scores should be comparable.**

In [545]:
from sklearn.model_selection import train_test_split
train, test = train_test_split(df, test_size=0.20)

In [546]:
X_train = train.drop(['is_attributed'], axis = 1)
y_train = train['is_attributed']

X_test = test.drop(['is_attributed'], axis = 1)
y_test = test['is_attributed']

In [547]:
print('Dimension of X_train:', X_train.shape)
print('Dimension of y_train:', y_train.shape)
print('Dimension of X_test:', X_test.shape)
print('Dimension of y_test:', y_test.shape)

Dimension of X_train: (80000, 8)
Dimension of y_train: (80000,)
Dimension of X_test: (20000, 8)
Dimension of y_test: (20000,)


In [548]:
## Section 6

**6. Apply XGBoostClassifier with default parameters on training data and make first 10 prediction for Test data.          NOTE: Use y_pred = model.predict_proba(X_test) since we need probabilities to compute AUC.** 

In [549]:
import xgboost as xgb
from xgboost import XGBClassifier

In [550]:
from sklearn.model_selection import train_test_split
traino, testo = train_test_split(df, test_size=0.20)

In [551]:
X_traino = traino.drop(['is_attributed'], axis = 1)
y_traino = traino['is_attributed']

X_testo = testo.drop(['is_attributed'], axis = 1)
y_testo = testo['is_attributed']

In [552]:
model = XGBClassifier()
model.fit(X_traino, y_traino)

XGBClassifier()

In [553]:
from sklearn.metrics import accuracy_score

In [554]:
y_predo = model.predict(X_testo)

In [555]:
y_testo.value_counts()

0    19952
1       48
Name: is_attributed, dtype: int64

In [556]:
y_predo

array([0, 0, 0, ..., 0, 0, 0])

In [557]:
from sklearn.metrics import roc_auc_score,confusion_matrix

auc_score5 = roc_auc_score(y_testo, y_predo)

print('AUC/ROC score by XGBClassifier is:', auc_score5)

AUC/ROC score by XGBClassifier is: 0.5624498797113071


In [558]:
model.score(X_testo,y_testo)

0.9978

In [559]:
from sklearn.metrics import classification_report
print(classification_report(y_testo,y_predo))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00     19952
           1       0.75      0.12      0.21        48

    accuracy                           1.00     20000
   macro avg       0.87      0.56      0.61     20000
weighted avg       1.00      1.00      1.00     20000



In [560]:
## Section 7

**7. On evaluating the predictions made by the model what is the AUC/ROC score with default hyperparameters.**

In [561]:
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split

X, y = make_classification(n_samples=100000, n_classes=2, n_features=20, random_state=20)

X_traina, X_testa, y_traina, y_testa = train_test_split(X, y, test_size=0.2, random_state=20)

In [562]:
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier

model1 = LogisticRegression()

model2 = KNeighborsClassifier(n_neighbors=4)

model1.fit(X_traina, y_traina)
model2.fit(X_traina, y_traina)

pred_prob1 = model1.predict_proba(X_testa)
pred_prob2 = model2.predict_proba(X_testa)

In [563]:
model1.score(X_testa, y_testa)

0.85235

In [564]:
from sklearn.metrics import roc_auc_score,confusion_matrix

auc_score1 = roc_auc_score(y_testa, pred_prob1[:,1])
auc_score2 = roc_auc_score(y_testa, pred_prob2[:,1])

print(auc_score1, auc_score2)

0.9207786406338052 0.9050560562972083


In [565]:
## Section 8

**8. Compute feature importance score and name the top 5 features/columns .**

In [566]:
# Constructing correlation Matrix
data_corr =df.corr()

In [567]:
# Considering only the features which have absolute correlation value greater than 0.0

data_corr = data_corr['is_attributed'][:-1]
data_corr[abs(data_corr)>=0.0].sort_values(ascending=False)

is_attributed    1.000000
app              0.064426
ip               0.054955
os               0.006183
device          -0.000695
channel         -0.023336
Name: is_attributed, dtype: float64

In [568]:
## Section 8
## SMOTE

In [569]:
from imblearn.over_sampling import SMOTE
sm = SMOTE()

In [570]:
x_sm, y_sm = sm.fit_resample(X, y)

In [571]:
X_train_sm, X_test_sm, y_train_sm, y_test_sm = train_test_split(x_sm,y_sm, test_size= 0.75)


In [572]:
from sklearn.ensemble import BaggingClassifier
model = BaggingClassifier(n_estimators=10)
model.fit(X_train_sm, y_train_sm)
y_predict = model.predict(X_test_sm)
print(accuracy_score(y_test_sm,y_predict))
print(confusion_matrix(y_test_sm,y_predict))


0.8994427558257345
[[34822  2608]
 [ 4935 32647]]


In [573]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model.fit(X_train_sm, y_train_sm)
y_predict1 = model.predict(X_test_sm)
print(accuracy_score(y_test_sm,y_predict1))
print(confusion_matrix(y_test_sm,y_predict1))

0.8554631258998561
[[32413  5017]
 [ 5825 31757]]


In [574]:
from sklearn.metrics import roc_auc_score,confusion_matrix

auc_score3 = roc_auc_score(y_test_sm, y_predict)
auc_score4 = roc_auc_score(y_test_sm, y_predict1)

print('AUC/ROC score by BaggingClassifer is:', auc_score3)
print('AUC/ROC score by LogisticClassifer is:', auc_score4)

AUC/ROC score by BaggingClassifer is: 0.8995052037818082
AUC/ROC score by LogisticClassifer is: 0.8554843594797921
